joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.12
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    # No deadman button required for normal driving.
    require_enable_button: false
    enable_button: 7  # Optional deadman (unused while require_enable_button is false)
    enable_turbo_button: 6  # Turbo when pressed
