teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 1.3
    scale_linear_turbo:
      x: 4.1

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 1.9

    enable_button: 7  # Left trigger button
    enable_turbo_button: 6  # Right trigger button